alias hostfile="code /etc/hosts"
alias sshconfig="code ~/.ssh/config"
alias zshconfig="code ~/.zshrc"
alias ohmyzsh="code ~/.oh-my-zsh"
alias occonfig="code ~/.config/opencode/opencode.json"
alias clconfig="code ~/.claude/CLAUDE.md"