alias phpstorm='open -a "PhpStorm.app" "$(pwd)"'
alias cl='command claude --dangerously-skip-permissions'
alias ct='claude --tmux --worktree --dangerously-skip-permissions'
alias opencode='command opencode2'
alias oc='opencode'
alias codex='command codex --ask-for-approval=never'
