export interface Component {
  id: string;
  label: string;
  category: string;
  default: boolean;
  required: boolean;
  dependencies?: string[];
  links?: string[];
  commands?: string[];
}

// Transcribed verbatim from internal/installer/manifest.go (Components()),
// with one mandated deviation (ADR-3 manifest consequence): base's
// `brew install go` command is removed so the catalog has no Go toolchain
// references. `xcode-select --install` is kept.
export const COMPONENTS: Component[] = [
  {
    id: "base",
    label: "Base tools",
    category: "Base",
    default: true,
    required: true,
    commands: ["xcode-select --install"],
  },
  {
    id: "shell",
    label: "Zsh and plugins",
    category: "Shell",
    default: true,
    required: true,
    links: ["zsh", "p10k"],
    commands: ["brew install zsh fzf", "dot zsh"],
  },
  {
    id: "git",
    label: "Git, SSH signing, Hunk and GitHub tools",
    category: "Git",
    default: true,
    required: true,
    links: ["git", "lazygit", "hunk"],
    commands: ["brew install git gh lazygit hunk", "dot git"],
  },
  {
    id: "terminal",
    label: "Terminal tools",
    category: "Terminal",
    default: true,
    required: true,
    links: ["ghostty", "tmux", "yazi"],
    commands: ["brew install --cask ghostty", "brew install tmux yazi neovim"],
  },
  {
    id: "php",
    label: "Composer, Herd and PHPStorm",
    category: "PHP",
    default: false,
    required: false,
    commands: ["brew install composer Herd", "brew install --cask phpstorm"],
  },
  {
    id: "service-mysql",
    label: "MySQL",
    category: "Services",
    default: false,
    required: false,
    commands: ["brew install mysql"],
  },
  {
    id: "service-postgresql",
    label: "PostgreSQL",
    category: "Services",
    default: false,
    required: false,
    commands: ["brew install postgresql"],
  },
  {
    id: "service-redis",
    label: "Redis",
    category: "Services",
    default: false,
    required: false,
    commands: ["brew install redis"],
  },
  {
    id: "service-sqlite",
    label: "SQLite",
    category: "Services",
    default: false,
    required: false,
    commands: ["brew install sqlite"],
  },
  {
    id: "ai",
    label: "AI tools",
    category: "AI",
    default: false,
    required: false,
    commands: ["brew install opencode"],
    links: ["claude", "agents"],
  },
  {
    id: "ai-herdr",
    label: "Herdr",
    category: "AI",
    default: false,
    required: false,
    commands: ["brew install herdr"],
    links: ["herdr"],
  },
  {
    id: "vscode",
    label: "VS Code",
    category: "Editors",
    default: false,
    required: false,
    commands: ["brew install --cask visual-studio-code", "dot code"],
    links: ["vscode"],
  },
  {
    id: "desktop-chrome",
    label: "Chrome",
    category: "Desktop",
    default: false,
    required: false,
    commands: ["brew install --cask google-chrome"],
  },
  {
    id: "desktop-firefox",
    label: "Firefox",
    category: "Desktop",
    default: false,
    required: false,
    commands: ["brew install --cask firefox"],
  },
  {
    id: "desktop-brave",
    label: "Brave",
    category: "Desktop",
    default: false,
    required: false,
    commands: ["brew install --cask brave-browser"],
  },
  {
    id: "communication-discord",
    label: "Discord",
    category: "Communication",
    default: false,
    required: false,
    commands: ["brew install --cask discord"],
  },
  {
    id: "communication-telegram",
    label: "Telegram",
    category: "Communication",
    default: false,
    required: false,
    commands: ["brew install --cask telegram"],
  },
  {
    id: "communication-whatsapp",
    label: "WhatsApp",
    category: "Communication",
    default: false,
    required: false,
    commands: ["brew install --cask whatsapp"],
  },
  {
    id: "communication-slack",
    label: "Slack",
    category: "Communication",
    default: false,
    required: false,
    commands: ["brew install --cask slack"],
  },
  {
    id: "desktop-raycast",
    label: "Raycast",
    category: "Desktop",
    default: false,
    required: false,
    commands: ["brew install --cask raycast"],
  },
  {
    id: "desktop-finetune",
    label: "Finetune",
    category: "Desktop",
    default: false,
    required: false,
    commands: ["brew install --cask finetune"],
  },
  {
    id: "desktop-typewhisper",
    label: "TypeWhisper",
    category: "Desktop",
    default: false,
    required: false,
    commands: ["brew install --cask typewhisper"],
  },
  {
    id: "desktop-rectangle",
    label: "Rectangle",
    category: "Desktop",
    default: false,
    required: false,
    commands: ["brew install --cask rectangle"],
  },
  {
    id: "desktop-aerospace",
    label: "Aerospace",
    category: "Desktop",
    default: false,
    required: false,
    links: ["aerospace"],
    commands: ["brew install --cask aerospace"],
  },
  {
    id: "desktop-linearmouse",
    label: "LinearMouse",
    category: "Desktop",
    default: false,
    required: false,
    links: ["linearmouse"],
    commands: ["brew install --cask linearmouse"],
  },
  {
    id: "desktop-localsend",
    label: "LocalSend",
    category: "Desktop",
    default: false,
    required: false,
    commands: ["brew install --cask localsend"],
  },
  {
    id: "media-tools",
    label: "Media command-line tools",
    category: "Media",
    default: false,
    required: false,
    commands: ["brew install ffmpeg ffmpegthumbnailer unar imagemagick webp"],
  },
  {
    id: "media-spotify",
    label: "Spotify",
    category: "Media",
    default: false,
    required: false,
    commands: ["brew install --cask spotify"],
  },
  {
    id: "media-stremio",
    label: "Stremio",
    category: "Media",
    default: false,
    required: false,
    commands: ["brew install --cask stremio"],
  },
  {
    id: "media-vlc",
    label: "VLC",
    category: "Media",
    default: false,
    required: false,
    commands: ["brew install --cask vlc"],
  },
  {
    id: "media-castor",
    label: "Castor",
    category: "Media",
    default: false,
    required: false,
    commands: ["brew install --cask stupside/tap/castor"],
  },
];
