# This file is copied into ~/.config/herdr/config.toml during installation

onboarding = false

[theme]
name = "catppuccin"

# Don't switch light/dark modes
auto_switch = false

[theme.custom]
accent = "#c6a0f6"
panel_bg = "#24273a"
surface0 = "#363a4f"
surface1 = "#494d64"
surface_dim = "#1e2030"
overlay0 = "#6e738d"
overlay1 = "#8087a2"
text = "#cad3f5"
subtext0 = "#a5adcb"
mauve = "#c6a0f6"
green = "#a6da95"
yellow = "#eed49f"
red = "#ed8796"
blue = "#8aadf4"
teal = "#8bd5ca"
peach = "#f5a97f"

[keys]
prefix = "ctrl+a"

# Jump straight to agent N (1..9) as listed in the sidebar.
focus_agent = "prefix+ctrl+1..9"

focus_pane_left = ["prefix+h"]
focus_pane_right = ["prefix+l"]
focus_pane_down = ["prefix+j"]
focus_pane_up = ["prefix+k"]

new_tab = "prefix+t"

new_worktree = "prefix+shift+n"
remove_worktree = "prefix+shift+d"

new_workspace = "prefix+n"
close_workspace = "prefix+d"

[ui]
show_agent_labels_on_pane_borders = true
prompt_new_tab_name = false
pane_gaps = false

mouse_capture = true
copy_on_select = true
host_cursor = "native"
right_click_passthrough_modifier = "ctrl"
mouse_scroll_lines = 1

status_indicators = "symbols"

[ui.toast]
delivery = "herdr"

[ui.toast.herdr]
position = "top-right"

[ui.toast.clipboard]
position = "top-right"

[ui.sound]
enabled = true

[ui.sidebar.spaces]
row_gap = 0
rows = [
  ["workspace", "branch", "git_status", "$ports"],
]

[ui.sidebar.agents]
row_gap = 0
rows = [
  ["state_icon", "workspace", "agent"],
  ["terminal_title_stripped"]
]

[terminal]
default_shell = "zsh"

[update]
channel = "preview"

[experimental]
kitty_graphics = true

[session]
resume_agents_on_restore = true


#################################################
#                                               #
#                Extensions                     #
#                                               #
#################################################

# --------------- Ports -----------------------
# Open the popup with prefix+a
[[keys.command]]
key = "prefix+a"
type = "plugin_action"
command = "numbered.ports.open"

# --------------- Scratch Terminal ------------
[[keys.command]]
key = "ctrl+shift+alt+cmd+t"
type = "plugin_action"
command = "maro114510.toggle-popup.toggle-shell"
description = "toggle scratch terminal"

# ---------------- NVim ----------------------
[[keys.command]]
key = "prefix+e"
type = "plugin_action"
command = "chmarax.herdr-nvim.toggle"
description = "nvim sidebar"

[[keys.command]]
key = "prefix+o"
type = "plugin_action"
command = "chmarax.herdr-nvim.pick-file"
description = "open file from agent output"
